version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
  test:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: decrypt credentials file
          # update locally with:
          # openssl aes-256-cbc -e -pbkdf2 -in gas-test-credentials.json -out encrypted-credentials -k $KEY
          command: openssl aes-256-cbc -d -pbkdf2 -in encrypted-credentials -k $KEY > gas-test-credentials.json
      - run:
          name: decrypt .clasprc.json
          # update locally with:
          # openssl aes-256-cbc -e -pbkdf2 -in ~/.clasprc.json -out ./.clasprc.json.encrypted -k $KEY
          command: openssl aes-256-cbc -d -pbkdf2 -in .clasprc.json.encrypted -k $KEY > $HOME/.clasprc.json
      - run: npm ci
      - run: mkdir -p test-results
      - run:
          name: Test
          command: npm test -- -r xunit -o test-results/result.xml --suppress_console
      - run: npx clasp logout
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
