# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - shell: bash
      # update locally with:
      # openssl aes-256-cbc -e -in ~/.clasprc.json -out ./.clasprc.json.encrypted -k $KEY
      run: openssl aes-256-cbc -d -in .clasprc.json.encrypted -k $KEY > $HOME/.clasprc.json
      env:
        KEY: ${{ secrets.KEY }}
    - shell: bash
      # update locally with:
      # openssl aes-256-cbc -e -in gas-test-credentials.json -out encrypted-credentials -k $KEY
      run: openssl aes-256-cbc -d -in encrypted-credentials -k $KEY > gas-test-credentials.json
      env:
        KEY: ${{ secrets.KEY }}
    - run: npm test
      env:
        CI: true
